# Automatically generated by configure - do not modify
SRC_PATH=/home/zp/share/qemu/roms/vgabios
AS=aarch64-linux-gnu-as
CC=aarch64-linux-gnu-gcc
BCC=bcc
CPP=aarch64-linux-gnu-gcc -E
OBJCOPY=objcopy
IASL=iasl
LD=aarch64-linux-gnu-ld
