# Automatically generated by configure - do not modify
TARGET_ARM=y
TARGET_NAME=arm
TARGET_BASE_ARCH=arm
TARGET_ABI_DIR=arm
CONFIG_KVM=y
CONFIG_VHOST_NET=y
CONFIG_SOFTMMU=y
TARGET_XML_FILES= /home/jl/virtual/qemu/gdb-xml/arm-core.xml /home/jl/virtual/qemu/gdb-xml/arm-vfp.xml /home/jl/virtual/qemu/gdb-xml/arm-vfp3.xml /home/jl/virtual/qemu/gdb-xml/arm-neon.xml
CONFIG_ARM_DIS=y
CONFIG_ARM_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
