/* Automatically generated by create_config - do not modify */
#define TARGET_ARM 1
#define TARGET_NAME "arm"
#define TARGET_ARM 1
#define CONFIG_KVM 1
#define CONFIG_VHOST_NET 1
#define CONFIG_SOFTMMU 1
#define CONFIG_ARM_DIS 1
#define CONFIG_ARM_DIS 1
