// Generated Code - DO NOT EDIT !!
// generated by 'emugen'

#include <string.h>
#include "renderControl_server_context.h"
#include <stdio.h>

int renderControl_server_context_t::initDispatchByName(void *(*getProc)(const char *, void *userData), void *userData)
{
	void *ptr;

	ptr = getProc("rcGetRendererVersion", userData); set_rcGetRendererVersion((rcGetRendererVersion_server_proc_t)ptr);
	ptr = getProc("rcGetEGLVersion", userData); set_rcGetEGLVersion((rcGetEGLVersion_server_proc_t)ptr);
	ptr = getProc("rcQueryEGLString", userData); set_rcQueryEGLString((rcQueryEGLString_server_proc_t)ptr);
	ptr = getProc("rcGetGLString", userData); set_rcGetGLString((rcGetGLString_server_proc_t)ptr);
	ptr = getProc("rcGetNumConfigs", userData); set_rcGetNumConfigs((rcGetNumConfigs_server_proc_t)ptr);
	ptr = getProc("rcGetConfigs", userData); set_rcGetConfigs((rcGetConfigs_server_proc_t)ptr);
	ptr = getProc("rcChooseConfig", userData); set_rcChooseConfig((rcChooseConfig_server_proc_t)ptr);
	ptr = getProc("rcGetFBParam", userData); set_rcGetFBParam((rcGetFBParam_server_proc_t)ptr);
	ptr = getProc("rcCreateContext", userData); set_rcCreateContext((rcCreateContext_server_proc_t)ptr);
	ptr = getProc("rcDestroyContext", userData); set_rcDestroyContext((rcDestroyContext_server_proc_t)ptr);
	ptr = getProc("rcCreateWindowSurface", userData); set_rcCreateWindowSurface((rcCreateWindowSurface_server_proc_t)ptr);
	ptr = getProc("rcDestroyWindowSurface", userData); set_rcDestroyWindowSurface((rcDestroyWindowSurface_server_proc_t)ptr);
	ptr = getProc("rcCreateColorBuffer", userData); set_rcCreateColorBuffer((rcCreateColorBuffer_server_proc_t)ptr);
	ptr = getProc("rcOpenColorBuffer", userData); set_rcOpenColorBuffer((rcOpenColorBuffer_server_proc_t)ptr);
	ptr = getProc("rcCloseColorBuffer", userData); set_rcCloseColorBuffer((rcCloseColorBuffer_server_proc_t)ptr);
	ptr = getProc("rcSetWindowColorBuffer", userData); set_rcSetWindowColorBuffer((rcSetWindowColorBuffer_server_proc_t)ptr);
	ptr = getProc("rcFlushWindowColorBuffer", userData); set_rcFlushWindowColorBuffer((rcFlushWindowColorBuffer_server_proc_t)ptr);
	ptr = getProc("rcMakeCurrent", userData); set_rcMakeCurrent((rcMakeCurrent_server_proc_t)ptr);
	ptr = getProc("rcFBPost", userData); set_rcFBPost((rcFBPost_server_proc_t)ptr);
	ptr = getProc("rcFBSetSwapInterval", userData); set_rcFBSetSwapInterval((rcFBSetSwapInterval_server_proc_t)ptr);
	ptr = getProc("rcBindTexture", userData); set_rcBindTexture((rcBindTexture_server_proc_t)ptr);
	ptr = getProc("rcBindRenderbuffer", userData); set_rcBindRenderbuffer((rcBindRenderbuffer_server_proc_t)ptr);
	ptr = getProc("rcColorBufferCacheFlush", userData); set_rcColorBufferCacheFlush((rcColorBufferCacheFlush_server_proc_t)ptr);
	ptr = getProc("rcReadColorBuffer", userData); set_rcReadColorBuffer((rcReadColorBuffer_server_proc_t)ptr);
	ptr = getProc("rcUpdateColorBuffer", userData); set_rcUpdateColorBuffer((rcUpdateColorBuffer_server_proc_t)ptr);
	ptr = getProc("rcOpenColorBuffer2", userData); set_rcOpenColorBuffer2((rcOpenColorBuffer2_server_proc_t)ptr);
	return 0;
}

