# Automatically generated by configure - do not modify
TARGET_AARCH64=y
TARGET_NAME=aarch64
TARGET_BASE_ARCH=arm
TARGET_ABI_DIR=aarch64
CONFIG_KVM=y
CONFIG_VHOST_NET=y
CONFIG_SOFTMMU=y
TARGET_XML_FILES= /home/zp/share/qemu/gdb-xml/aarch64-core.xml /home/zp/share/qemu/gdb-xml/aarch64-fpu.xml /home/zp/share/qemu/gdb-xml/arm-core.xml /home/zp/share/qemu/gdb-xml/arm-vfp.xml /home/zp/share/qemu/gdb-xml/arm-vfp3.xml /home/zp/share/qemu/gdb-xml/arm-neon.xml
CONFIG_ARM_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
